/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adivinha;

/**
 *
 * @author Marcela
 */
public class Jogo extends javax.swing.JFrame {

    /**
     * Creates new form Jogo
     */
    public Jogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNum = new javax.swing.JSpinner();
        tbJogar = new javax.swing.JButton();
        lblAdivinha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNum.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 131, 68, 43));

        tbJogar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbJogar.setText("Jogar");
        tbJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbJogarActionPerformed(evt);
            }
        });
        getContentPane().add(tbJogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 234, 97, 42));

        lblAdivinha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAdivinha.setText("Adivinha qual número estou pensando de 1 a 5...");
        getContentPane().add(lblAdivinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 424, 39));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pensando.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbJogarActionPerformed
        // TODO add your handling code here:
        int nun = Integer.parseInt(txtNum.getValue().toString());
        double pc = 1 + Math.random() * (6 - 1);
        int comp = (int) pc;
        String evento = (nun == comp)?"Voce Ganhou eu pensei no numero "+comp:"Voce perdeu eu pensei no número "+comp;
        lblAdivinha.setText(evento);
        
        
    }//GEN-LAST:event_tbJogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAdivinha;
    private javax.swing.JButton tbJogar;
    private javax.swing.JSpinner txtNum;
    // End of variables declaration//GEN-END:variables
}
